name: dailyreport

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Using a self-hosted runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Ensure the latest checkout action is used

      - name: Set up Python
        uses: actions/setup-python@v3  # Ensure the latest setup-python action is used
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}  # Ensure these secrets are set in GitHub
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          # Ensure send_email.py is in the correct directory or provide the path
          python send_email.py
