nexus:
  env:
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "false"
  # Minikube specific: adjust resources if your laptop is struggling
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

persistence:
  enabled: true
  storageClass: "standard" # Minikube default storage class
  size: 8Gi

# Use NodePort for easy access in Minikube without an Ingress controller
service:
  type: NodePort
