name: dailyreport

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # REMOVED actions/setup-python step as it is incompatible with Rocky Linux

      - name: Install dependencies
        run: |
          # Use python3.9 explicitly to ensure the correct environment
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install -r requirements.txt

      - name: Run the email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          # Use python3.9 to execute your script
          python3.9 send_email.py
