name: dailyreport

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies and Run
        env:
          # These must match exactly the names in Settings -> Secrets -> Actions
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          # 1. Create a virtual environment
          python3.9 -m venv venv
          
          # 2. Install dependencies into that environment
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt
          
          # 3. Run the script using the virtual environment's python
          ./venv/bin/python send_email.py
