name: Flow 1 - Event Driven

on:
  push:
    branches:
      - development

jobs:
  job1:
    runs-on: localhost
    steps:
      - name: Run Flow 1
        run: echo "Flow 1 triggered by push event"

